name: CodeStatistics
description: Gathers statistics into interactable MD files for code in a project
author: jojo2357

branding:
  color: orange
  icon: code

inputs:
  root_dir:
    description: The root directory of code to analyze
    required: false
    default: ''
  langs:
    description: The languages to apply statistics on
    required: false
    default: ''
  exclude:
    description: Pipe (|) seperated directories to ignore
    required: false
    default: ''

runs:
  using: node12
  main: RunMe.js
